src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "CIN should not be blank.")]
    #[Assert\Type(type: "integer", message: "CIN should be a valid {{ type }}. {{ value }} given.")]
    private ?int $cin = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Nom should not be blank.")]
    #[Assert\Regex(pattern: '/^[a-zA-Z ]+$/', message: "Nom should be a valid {{ type }}. {{ value }} given.")]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Prenom should not be blank.")]
    #[Assert\Regex(pattern: '/^[a-zA-Z ]+$/', message: "Prenom should be a valid {{ type }}. {{ value }} given.")]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Ville should not be blank.")]
    #[Assert\Regex(pattern: '/^[a-zA-Z ]+$/', message: "Ville should be a valid {{ type }}. {{ value }} given.")]
    private ?string $ville = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Num_tel should not be blank.")]
    #[Assert\Type(type: "integer", message: "Num_tel should be a valid {{ type }}. {{ value }} given.")]
    private ?int $num_tel = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Adresse_m should not be blank.")]
    private ?string $adresse_m = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Date_livraison should not be blank.")]
    #[Assert\Type(type: "\DateTimeImmutable", message: "Date_livraison should be a valid {{ type }}. {{ value }} given.")]
    private ?\DateTimeImmutable $date_livraison = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Type_produit should not be blank.")]
    #[Assert\Regex(pattern: '/^[a-zA-Z ]+$/', message: "Type_produit should be a valid {{ type }}. {{ value }} given.")]
    private ?string $type_produit = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Lieu_depart should not be blank.")]
    #[Assert\Regex(pattern: '/^[a-zA-Z ]+$/', message: "Lieu_depart should be a valid {{ type }}. {{ value }} given.")]
    private ?string $lieu_depart = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Lieu_arrivee should not be blank.")]
    #[Assert\Regex(pattern: '/^[a-zA-Z ]+$/', message: "Lieu_arrivee should be a valid {{ type }}. {{ value }} given.")]
    private ?string $lieu_arrivee = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Poids should not be blank.")]
    #[Assert\Type(type: "integer", message: "Poids should be a valid {{ type }}. {{ value }} given.")]
    private ?int $poids = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Drone $drone = null;

    // getters and setters ...

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCin(): ?int
    {
        return $this->cin;
    }

    public function setCin(int $cin): self
    {
        $this->cin = $cin;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getNumTel(): ?int
    {
        return $this->num_tel;
    }

    public function setNumTel(int $num_tel): self
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    public function getAdresseM(): ?string
    {
        return $this->adresse_m;
    }

    public function setAdresseM(string $adresse_m): self
    {
        $this->adresse_m = $adresse_m;

        return $this;
    }

    public function getDateLivraison(): ?\DateTimeImmutable
    {
        return $this->date_livraison;
    }

    public function setDateLivraison(\DateTimeImmutable $date_livraison): self
    {
        $this->date_livraison = $date_livraison;

        return $this;
    }

    public function getTypeProduit(): ?string
    {
        return $this->type_produit;
    }

    public function setTypeProduit(string $type_produit): self
    {
        $this->type_produit = $type_produit;

        return $this;
    }

    public function getLieuDepart(): ?string
    {
        return $this->lieu_depart;
    }

    public function setLieuDepart(string $lieu_depart): self
    {
        $this->lieu_depart = $lieu_depart;

        return $this;
    }

    public function getLieuArrivee(): ?string
    {
        return $this->lieu_arrivee;
    }

    public function setLieuArrivee(string $lieu_arrivee): self
    {
        $this->lieu_arrivee = $lieu_arrivee;

        return $this;
    }

    public function getPoids(): ?int
    {
        return $this->poids;
    }

    public function setPoids(int $poids): self
    {
        $this->poids = $poids;

        return $this;
    }

    public function getDrone(): ?Drone
    {
        return $this->drone;
    }

    public function setDrone(?Drone $drone): self
    {
        $this->drone = $drone;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('cin')
            ->add('nom')
            ->add('prenom')
            ->add('ville')
            ->add('num_tel')
            ->add('adresse_m')
            ->add('date_livraison')
            ->add('type_produit')
            ->add('lieu_depart')
            ->add('lieu_arrivee')
            ->add('poids')
            ->add('drone')

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Knp\Bundle\SnappyBundle\KnpSnappyBundle;
use Dompdf\Dompdf;
use App\Service\PDFgenerator;
use Knp\Component\Pager\Pagination\SlidingPaginationInterface;
use MercurySeries\FlashyBundle\FlashyNotifier;
use Symfony\Component\HttpFoundation\JsonResponse;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityManagerInterface;

#[Route('/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/', name: 'app_reservation_index', methods: ['GET'])]
// src/Controller/ReservationController.php

public function index(EntityManagerInterface $entityManager, Request $request, PaginatorInterface $paginator): Response
{
    $queryBuilder = $entityManager->createQueryBuilder()
        ->select('r')
        ->from(Reservation::class, 'r')
        ->orderBy('r.nom', 'ASC');

    $pagination = $paginator->paginate(
        $queryBuilder,
        $request->query->getInt('page', 1),
        
    );

    return $this->render('reservation/index.html.twig', [
        'reservations' => $pagination,
    ]);
}






    #[Route('/generate-pdf', name: 'app_reservation_generate_pdf', methods: ['GET'])]
public function generatePdf(ReservationRepository $reservationRepository): Response
{
    // Récupération des données de la base de données
    $reservations = $reservationRepository->findAll();

    $reservationData = [];

    foreach ($reservations as $reservation) {
        $reservationData[] = [
            'id' => $reservation->getId(),
            'cin' => $reservation->getCin(),
            'nom' => $reservation->getNom(),
            'prenom' => $reservation->getPrenom(),
            'ville' => $reservation->getVille(),
            'num_tel' => $reservation->getNumtel(),
            'adresse_m' => $reservation->getAdressem(),
            'date_livraison' => $reservation->getDatelivraison(),
            'type_produit' => $reservation->getTypeproduit(),
            'lieu_depart' => $reservation->getLieudepart(),
            'lieu_arrivee' => $reservation->getLieuarrivee(),
            'poids' => $reservation->getPoids()
            
            // Ajouter d'autres propriétés si nécessaire
        ];
    }

    $html = $this->renderView('reservation/generatepdf.html.twig', [
        'reservationData' => $reservationData,
    ]);

    $dompdf = new Dompdf();
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    $pdfContent = $dompdf->output();

    $response = new Response();
    $response->setContent($pdfContent);
    $response->headers->set('Content-Type', 'application/pdf');
    $response->headers->set('Content-Disposition', 'attachment;filename=reservation.pdf');

    return $response;
}

#[Route('/recherchereservation', name: 'app_reservation_recherche')]
public function rechercheRes(ReservationRepository $reservationRepository, Request  $request): Response
{
    $data=$request->get('search');
    $reservation = $reservationRepository->searchQB($data);
    return $this->render('reservation/index.html.twig',
        ["reservations" => $reservation]);
}
   
    
    
    #[Route('/new', name: 'app_reservation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReservationRepository $reservationRepository): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->save($reservation, true);

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }
    
    #[Route('/{id}', name: 'app_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation, FlashyNotifier $flashy): Response
    {   
        // ...
        
        $flashy->success('Voici la reservation que vous voulez voir  !');
        
        // ...
        
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }
    
    

    #[Route('/{id}/edit', name: 'app_reservation_edit', methods: ['GET', 'POST'])]
public function edit(Request $request, Reservation $reservation, ReservationRepository $reservationRepository, FlashyNotifier $flashy): Response
{
    $form = $this->createForm(ReservationType::class, $reservation);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $reservationRepository->save($reservation, true);

        $flashy->success('Réservation modifiée avec succès !');

        return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
    }

    return $this->renderForm('reservation/edit.html.twig', [
        'reservation' => $reservation,
        'form' => $form,
    ]);
}

    #[Route('/{id}', name: 'app_reservation_delete', methods: ['POST'])]
public function delete(Request $request, Reservation $reservation, ReservationRepository $reservationRepository, FlashyNotifier $flashy): Response
{
    if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
        
        // Supprime la réservation
        $reservationRepository->remove($reservation, true);

        // Affiche un message de confirmation
        $flashy->warning('La réservation a été supprimée avec succès !');
    }

    return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
}
#[Route('/map', name: 'app_reservation_map')]
    public function showMap(): Response
    {
        return $this->render('reservation/map.html.twig', [
            
        ]);
    }
    #[Route('/show_in_map/{id}', name: 'app_reservation_map', methods: ['GET'])]
    public function Map( Reservation $id,EntityManagerInterface $entityManager ): Response
    {

        $reservation = $entityManager
            ->getRepository(Reservation::class)->findBy( 
                ['id'=>$id]
            );
        return $this->render('map/api_arcgis.html.twig', [
            'reservation' => $reservation,
        ]);
    }
}









    

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button "class=btn btn-primary">Delete</button>
</form>

templates/reservation/_form.html.twig
{{form_start(form,{'attr':{'novalidate':'novalidate' , 'class' : 'reservation' }})}}

    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_index') }} "class="btn btn-primary">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
      
{% endblock %}

templates/reservation/front.html.twig
{% extends 'commande.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    
{% endblock %}

templates/reservation/generatepdf.html.twig
<html>
<head>
    <title>Mon PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            color: #333;
        }
        h1 {
            font-size: 20px;
            color: #0066cc;
        }
        table {
  border-collapse: collapse;
  width: 100%;
  margin-bottom: 20px;
  border: 1px solid #ddd;
}

th, td {
  padding: 8px;
  text-align: left;
  border-bottom: 1px solid #ddd;
}

th {
  background-color: #f2f2f2;
}

tr:nth-child(even) {
  background-color: #f9f9f9;
}

tr:hover {
  background-color: #f5f5f5;
}

td {
  border-right: 1px solid #ddd;
  border-left: 1px solid #ddd;
}

td:last-child {
  border-right: none;
}

th:first-child,
td:first-child {
  border-left: none;
}

th:last-child,
td:last-child {
  border-right: none;
}
        
    </style>
</head>
<body>
 
    <h1>Le PDF de vos réservations :</h1>
<p>Voici la liste de toutes vos réservations effectuées jusqu'à présent.</p>

   
    
    <h1>Reservation :</h1>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Cin</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Ville</th>
                <th>Num_tel</th>
                <th>Adresse_m</th>
                <th>Date livraison</th>
                <th>Type produit</th>
                <th>Lieu depart</th>
                <th>Lieu arrivee</th>
                <th>Poids</th>
            </tr>
        </thead>
        <tbody>
            {% for reservation in reservationData %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.cin }}</td>
                <td>{{ reservation.nom }}</td>
                <td>{{ reservation.prenom }}</td>
                <td>{{ reservation.ville }}</td>
                <td>{{ reservation.num_tel }}</td>
                <td>{{ reservation.adresse_m }}</td>
                <td>{{ reservation.date_livraison ? reservation.date_livraison|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ reservation.type_produit }}</td>
                <td>{{ reservation.lieu_depart }}</td>
                <td>{{ reservation.lieu_arrivee }}</td>
                <td>{{ reservation.poids }}</td>
            </tr>
            {% else %}
            <tr>
                <td colspan="12">Aucune reservation trouvée.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</body>
</html>

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}Reservation {% endblock %}

{% block body %}
    
    <h1>Reservation : </h1>

    <table class="table">
        <thead>
            <tr>
                <th>{{ knp_pagination_sortable(reservation, 'ID','reservation.id')}}</th>
                <th>{{ knp_pagination_sortable(reservation, 'Cin','reservation.cin')}}</th>
                <th>{{ knp_pagination_sortable(reservation, 'Nom','reservation.nom')}}</th>
                <th>{{ knp_pagination_sortable(reservation, 'Prenom','reservation.prenom')}}</th>
                <th>{{ knp_pagination_sortable(reservation, 'Ville','reservation.ville')}}</th>
                <th>{{ knp_pagination_sortable(reservation, 'Num_tel','reservation.num_tel')}}</th>
                <th>{{ knp_pagination_sortable(reservation, 'Adresse_m','reservation.adreese_m')}}</th>
                <th>{{ knp_pagination_sortable(reservation, 'Date livraison','reservation.date_livraison')}}</th>
                <th>{{ knp_pagination_sortable(reservation, 'Type produit','reservation.type_produit')}}</th>
                <th>{{ knp_pagination_sortable(reservation, 'Lieu depart','reservation.lieu_depart')}}</th>
                <th>{{ knp_pagination_sortable(reservation, 'Lieu arrivee','reservation.lieu_arrivee')}}</th>
                <th>{{ knp_pagination_sortable(reservation, 'Poids','reservation.poids')}}</th>
                <th>Drone</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservation %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.cin }}</td>
                <td>{{ reservation.nom }}</td>
                <td>{{ reservation.prenom }}</td>
                <td>{{ reservation.ville }}</td>
                <td>{{ reservation.numTel }}</td>
                <td>{{ reservation.adresseM }}</td>
                <td>{{ reservation.dateLivraison ? reservation.dateLivraison|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ reservation.typeProduit }}</td>
                <td>{{ reservation.lieuDepart }}</td>
                <td>{{ reservation.lieuArrivee }}</td>
                <td>{{ reservation.poids }}</td>
                <td>{{ reservation.drone }}</td>
                <td>
                    <a href="{{ path('app_reservation_show', {'id': reservation.id}) }} "class="btn btn-primary">show</a>
                    <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}"class="btn btn-primary">edit</a>
                <button style="background-color: #4CAF50; color: white; padding: 10px 20px; border: none; border-radius: 4px;">
  <a href="{{ path('app_reservation_generate_pdf') }}" style="color: white; text-decoration: none;">Télécharger le PDF</a>
</button>




                    
                     
                    
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
                
        </tbody>
    </table>
    
    <style>
        
        body {
            font-family: Arial, sans-serif;
        }
        h1 {
            color: #007bff;
            text-align: center;
        }
    </style>
    
    
    <div class="navigation text-center">
    {{ knp_pagination_render(reservation) }}
    </div>
    
{% endblock %}

templates/reservation/new.html.twig
{% extends 'commande.html.twig' %}

{% block title %}New reservation{% endblock %}

{% block body %}
    <h1>Create new reservation</h1>

    {{ include('reservation/_form.html.twig') }}
    
    
{% endblock %}

templates/reservation/recherche.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
<h1 class="text-center mb-4">Réservations</h1>
<div class="table-responsive">
    <table class="table" id="myTable">
        <thead>
            <tr>
                <th>ID</th>
                <th>CIN</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Ville</th>
                <th>Numéro de téléphone</th>
                <th>Adresse mail</th>
                <th>Date de livraison</th>
                <th>Type de produit</th>
                <th>Lieu de départ</th>
                <th>Lieu d'arrivée</th>
                <th>Poids</th>
                <th>Drone</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
          <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" method="post" action="{{ path('app_reservation_recherche') }}">
                        <div class="input-group">
                            <input name="search" type="text" class="form-control bg-light border-0 small js-search-input" placeholder="Recherche selon le nom ou la ville ou le prenom..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            {# <input value="Recherche" type="submit" class="form-control bg-light border-0 small"> #}
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>

                    </form>
                    
                    </nav>
         {% for res in reservations %}
            <tr>
                <td>{{ res.id }}</td>
                <td>{{ res.cin }}</td>
                <td>{{ res.nom }}</td>
                <td>{{ res.prenom }}</td>
                <td>{{ res.ville }}</td>
                <td>{{ res.numTel }}</td>
                <td>{{ res.adresseM }}</td>
                <td>{{ res.dateLivraison ? res.dateLivraison|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ res.typeProduit }}</td>
                <td>{{ res.lieuDepart }}</td>
                <td>{{ res.lieuArrivee }}</td>
                <td>{{ res.poids }}</td>
                <td>{{ res.drone }}</td>
                <td>
                    <div class="d-flex flex-wrap">
                        <a href="{{ path('app_reservation_show', {'id': res.id}) }}" class="btn btn-sm btn-primary me-2 mb-2">Voir</a>
                        <a href="{{ path('app_reservation_edit', {'id': res.id}) }}" class="btn btn-sm btn-primary me-2 mb-2">Modifier</a>
                        <a href="{{ path('app_reservation_map', {'id': res.id}) }}" class="btn btn-sm btn-info me-2 mb-2">Localisation</a>
                        <a href="{{ path('app_reservation_generate_pdf') }}" class="btn btn-sm btn-success me-2 mb-2">Télécharger PDF</a>
                  


                    </div>
                </td>
            </tr>
            {% else %}
            <tr>
                <td colspan="14">Aucun enregistrement trouvé.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



<style>
    body {
        font-family: Arial, sans-serif;
    }

    h1 {
        color: #007bff;
        text-align: center;
    }

    .table {
        margin-top: 2rem;
    }

    .btn {
        font-size: 0.8rem;
    }
</style>

{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>
    
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Cin</th>
                <td>{{ reservation.cin }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ reservation.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ reservation.prenom }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ reservation.ville }}</td>
                
            </tr>
            <tr>
                <th>Num_tel</th>
                <td>{{ reservation.numTel }}</td>
                
            </tr>
            <tr>
                <th>Adresse_m</th>
                <td>{{ reservation.adresseM }}</td>
            </tr>
            <tr>
                <th>Date_livraison</th>
                <td>{{ reservation.dateLivraison ? reservation.dateLivraison|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Type_produit</th>
                <td>{{ reservation.typeProduit }}</td>
            </tr>
            <tr>
                <th>Lieu_depart</th>
                <td>{{ reservation.lieuDepart }}</td>
            </tr>
            <tr>
                <th>Lieu_arrivee</th>
                <td>{{ reservation.lieuArrivee }}</td>
            </tr>
            <tr>
                <th>Poids</th>
                <td>{{ reservation.poids }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reservation_index') }} "class="btn btn-primary">back to list</a>

    <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}"class="btn btn-primary">edit</a>
    

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}